//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaimDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CauseType
    {
        public CauseType()
        {
            this.Claims = new HashSet<Claim>();
        }
    
        public int CauseTypeId { get; set; }
        public string CauseTypeCode { get; set; }
    
        public virtual ICollection<Claim> Claims { get; set; }
    }
}
