//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaimDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaimVechicle
    {
        public int ClaimVehicleId { get; set; }
        public int ClaimId { get; set; }
        public int VehicleId { get; set; }
    
        public virtual Claim Claim { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
