//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaimDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClaimDatabaseEntities : DbContext
    {
        public ClaimDatabaseEntities()
            : base("name=ClaimDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CauseType> CauseTypes { get; set; }
        public DbSet<Claim> Claims { get; set; }
        public DbSet<ClaimStatusType> ClaimStatusTypes { get; set; }
        public DbSet<ClaimVechicle> ClaimVechicles { get; set; }
        public DbSet<Vehicle> Vehicles { get; set; }
    }
}
