//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaimDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Claim
    {
        public Claim()
        {
            this.ClaimVechicles = new HashSet<ClaimVechicle>();
        }
    
        public int ClaimId { get; set; }
        public string ClaimNumber { get; set; }
        public string ClaimantFirstName { get; set; }
        public string ClaimantLastName { get; set; }
        public Nullable<int> ClaimStatus { get; set; }
        public Nullable<long> AssignedAdjusterID { get; set; }
        public Nullable<int> CauseOfLoss { get; set; }
        public Nullable<System.DateTime> ReportedDate { get; set; }
        public string LossDescription { get; set; }
        public Nullable<System.DateTime> LossDate { get; set; }
    
        public virtual CauseType CauseType { get; set; }
        public virtual ClaimStatusType ClaimStatusType { get; set; }
        public virtual ICollection<ClaimVechicle> ClaimVechicles { get; set; }
    }
}
